import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import { device } from "../utils/breakpoints";
import { AiFillInstagram } from "react-icons/ai";
import { BsFacebook } from "react-icons/bs";
import { GrMail } from "react-icons/gr";
import { Parallax } from "react-parallax";
import { contactOutlets } from "../data";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Ubuntu Vegan Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Hero>
          <img src="/images/heroMain.png" alt="" />
          <Content>
            <div className="banner">
              <div className="title">
                <p>
                  Plant-Based Cafe <span>&</span>
                </p>

                <p>Cloud Kitchen</p>
              </div>
              <p className="subtitle">
                Creating a <span>Kindelicious</span> world by improving what we
                EAT!🌱
              </p>
              <Socials>
                <a href="https://www.instagram.com/ubuntueat/" target="_blank">
                  <AiFillInstagram fontSize={25} className="icons" />
                </a>
                <a href="https://www.facebook.com/ubuntueat/" target="_blank">
                  <BsFacebook fontSize={22} className="icons" />
                </a>
                <GrMail
                  fontSize={24}
                  className="icons"
                  onClick={() =>
                    window.open("mailto:  ubuntucommunity3@gmail.com")
                  }
                />
              </Socials>
            </div>
            <OrderBtn>Order Now</OrderBtn>
          </Content>
        </Hero>
      </header>
      <Parallax
        className="parallexBg"
        // blur={10}
        bgImage="/images/bongGuy.png"
        bgImageAlt="cloud kitchen"
        strength={300}
      >
        <div className="innerWrapper">
          <ContactCard>
            <p className="message">
              We have excitement waiting for you when you order directly from us
            </p>
            <div className="contacts">
              {contactOutlets.map((contact) => (
                <>
                  <div className="singleContact">
                    {contact.icon}
                    <p className="text">{contact.message}</p>
                    <p className="info">{contact.info}</p>
                  </div>
                  <hr />
                </>
              ))}
            </div>
            <div className="edges top-top"></div>
            <div className="edges top-right"></div>
            <div className="edges bottom-left"></div>
            <div className="edges bottom-bottom"></div>
          </ContactCard>
        </div>
      </Parallax>
    </Container>
  );
};

export default Home;

const Container = styled.div`
  .parallexBg {
    .innerWrapper {
      background: rgba(0, 0, 0, 0.87);
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 3rem 0;

      @media ${device.lg} {
        padding: 8rem 0;
      }
    }
  }
`;

const Hero = styled.header`
  width: 100%;
  height: 100vh;
  position: relative;

  img {
    height: 100%;
    width: 100%;
    object-fit: cover;
  }

  &:after {
    background: linear-gradient(
      180deg,
      #dec59c 32.29%,
      rgba(222, 197, 156, 0) 100%
    );

    position: absolute;
    content: "";
    top: 0;
    left: 0;
    color: white;

    width: 100%;
    height: 100%;

    @media ${device.lg} {
      background: linear-gradient(
        89.49deg,
        #dec59c 14.85%,
        rgba(222, 197, 156, 0) 62.35%
      );
    }
  }
`;

const Content = styled.div`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 50;
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-direction: column;
  gap: 2rem;
  padding: var(--padding-x-base);
  padding-top: 15vh;
  padding-bottom: 12vh;

  @media ${device.lg} {
    align-items: flex-start;
    justify-content: center;
  }

  .banner {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2rem;
    margin-top: 3rem;
    position: relative;

    @media ${device.lg} {
      align-items: flex-start;
      // justify-content: center;
      margin: 0 11rem;
      margin-top: 3rem;
    }

    @media ${device.xl} {
      margin: 0 13rem;
      margin-top: 3rem;
    }
  }

  .title {
    display: flex;
    flex-direction: column;
    align-items: center;
    font-family: var(--font-sans-3);
    font-size: 2.5rem;

    span {
      display: block;
      text-align: center;
      @media ${device.lg} {
        display: inline;
      }
    }

    @media ${device.lg} {
      font-size: 3.2rem;
      align-items: flex-start;
    }
  }

  .subtitle {
    text-align: center;
    font-size: 1.2rem;
    font-family: var(--font-subtitle);
    font-weight: bold;
    max-width: 350px;
    line-height: 150%;

    @media ${device.lg} {
      text-align: left;
      font-style: normal;
      font-size: 1.3rem;
    }

    span {
      color: #b3594c;
    }
  }
`;

const Socials = styled.div`
  display: flex;
  align-items: center;
  gap: 1.2rem;
  margin-top: 2rem;

  color: var(--col-secondary);
  @media ${device.lg} {
    position: absolute;
    left: -40%;
    top: 50%;
    transform: rotate(90deg) translateX(-40%);
  }

  .icons {
    cursor: pointer;
    opacity: 0.9;
    @media ${device.lg} {
      transform: rotate(-90deg) scale(0.8);
    }
  }
`;

const OrderBtn = styled.button`
  padding: 0.7rem 2rem;
  color: white;
  background: var(--col-accent);
  border-radius: 0.3rem;
  text-transform: capitalize;
  cursor: pointer;
  border: none;
  font-size: 1.3rem;

  @media ${device.lg} {
    display: none;
  }
`;

const ContactCard = styled.div`
  background: rgba(7, 12, 14, 0.63);
  width: 100%;
  height: 100%;
  color: white;
  padding: 4rem 2rem;
  max-width: 40rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 5rem;
  position: relative;
  z-index: 1;
  .edges {
    display: none;
  }
  @media ${device.lg} {
    .edges {
      display: block;
      position: absolute;
      width: 6rem;
      height: 0.2rem;
      background: var(--col-highlight);
    }

    .top-top {
      top: 0;
      right: 0;
    }
    .top-right {
      right: 0;
      top: 0;
      height: 6rem;
      width: 0.2rem;
    }
    .bottom-bottom {
      bottom: 0;
      left: 0;
    }
    .bottom-left {
      left: 0;
      bottom: 0;
      height: 6rem;
      width: 0.2rem;
    }
  }

  .message {
    text-align: center;
    font-size: 1.6rem;
    max-width: 80%;
    line-height: 150%;
    font-family: var(--font-body);
  }

  .contacts {
    display: flex;
    flex-direction: column;
    gap: 4rem;

    @media ${device.lg} {
      flex-direction: row;
    }

    hr {
      height: 2px;
      background: var(--col-highlight);
      border: none;

      @media ${device.lg} {
        height: auto;
        width: 2px;
      }

      &:last-of-type {
        display: none;
      }
    }

    .singleContact {
      display: flex;
      flex-direction: column;
      align-items: center;
      font-family: var(--font-highlight);
      .icon {
        font-size: 1.8rem;
      }
      .text {
        margin: 2rem 0 0.7rem;
        text-transform: capitalize;
        font-size: 1.1rem;
      }
      .info {
        color: var(--col-highlight);
        font-size: 1.3rem;
      }
    }
  }
`;
